version: 0.2
phases:
 install:
   commands:
     - sed -i "s/CODEBUILD_BUILD_ID/$CODEBUILD_BUILD_ID/g" ./container/cfn-master.yaml
 pre_build:
   commands:
     - chmod +x ./scripts/validate-template.sh
     - ./scripts/validate-template.sh
 build:
   commands:
    - aws s3 sync --delete . "s3://hdm.cloud" --exclude "*.y*ml" --acl "public-read"
    - aws s3 cp container s3://hdm-s3-common-s3bucket-okportar9irk/$CODEBUILD_BUILD_ID/ --recursive
 post_build:
   commands:
     - echo "post_build step"
     - aws s3 rm s3://hdm.cloud/terraform --recursive
     - aws s3 rm s3://hdm.cloud/scripts --recursive
     - aws s3 rm s3://hdm.cloud/Dockerfile
     - aws s3 rm s3://hdm.cloud/README.md
     - aws s3 rm s3://hdm.cloud/packer.json