version: 0.2

env:
  variables:
    TF_VERSION: "0.11.11"

phases:
 install:
   commands:
     - export CODEBUILD_GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
     - |
       if [ "$CODEBUILD_GIT_BRANCH" = "" ] ; then
          CODEBUILD_GIT_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export CODEBUILD_GIT_BRANCH=${CODEBUILD_GIT_BRANCH#remotes/origin/};
       fi
     - cd /usr/bin
     - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
     - unzip -o terraform.zip
     - export GITHUB_TOKEN=$(aws ssm get-parameter --name "github_token" --with-decryption --output text --query 'Parameter.Value')
     - cd $CODEBUILD_SRC_DIR
     - sed -i "s/CODEBUILD_BUILD_ID/$CODEBUILD_BUILD_ID/g" ./aws/cfn-master.yaml
     - |
        if [ "$CODEBUILD_GIT_BRANCH" = "master" ]
        then
            export BUCKET_NAME="hdm.cloud"
        else
            export BUCKET_NAME="beta.hdm.cloud"
        fi

 pre_build:
   commands:
     - chmod +x ./scripts/validate-template.sh
     - ./scripts/validate-template.sh
     - make terraform-init
     - make terraform-validate
 build:
   commands:
    - aws s3 sync --delete . "s3://$BUCKET_NAME" --exclude "*.y*ml" --acl "public-read"
    - aws s3 cp aws s3://hdm-s3-common-s3bucket-okportar9irk/$CODEBUILD_BUILD_ID/ --recursive
 post_build:
   commands:
     - echo "post_build step"
     - aws s3 rm "s3://$BUCKET_NAME/terraform" --recursive
     - aws s3 rm "s3://$BUCKET_NAME/scripts" --recursive
     - aws s3 rm "s3://$BUCKET_NAME/Dockerfile"
     - aws s3 rm "s3://$BUCKET_NAME/README.md"
     - aws s3 rm "s3://$BUCKET_NAME/packer.json"